---
- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    debug:
      msg: OpenStack servers

  - name: Curl website
    debug:
      msg: Curl website

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
     msg: "The curl command was Failed"
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
...
